# Generated by Django 5.2.1 on 2025-05-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Customer', 'customer'), ('admin', 'Admin'), ('worker', 'Worker')], max_length=20),
        ),
    ]
